import { getPool, sql } from "../../config/database";
import type { ConnectionPool, Request } from "mssql";

import { FORM_CONFIGS } from "./input-form.config";
import type {
  FormConfig,
  FormName,
  InputFormRecord,
} from "./input-form.types";

/**
 * Returns the configuration for the requested input form.
 *
 * FORM_CONFIGS is the single source of truth for:
 * - Database table
 * - Primary key
 * - ChildID column
 * - Writable columns
 */
function cfg(name: FormName): FormConfig {
  const c = FORM_CONFIGS[name];

  if (!c) {
    throw new Error(`Unsupported form: ${name}`);
  }

  return c;
}

/**
 * Removes fields that are not allowed to be written to the
 * configured database table.
 *
 * The form primary key is also excluded because it should be
 * generated by SQL Server when the column is an IDENTITY column,
 * or generated by nextId() when it is not.
 */
function clean(
  c: FormConfig,
  p: InputFormRecord,
): InputFormRecord {
  const allowed = new Set(c.writableColumns);

  return Object.fromEntries(
    Object.entries(p).filter(
      ([key]) => allowed.has(key) && key !== c.idColumn,
    ),
  );
}

/**
 * Determines whether the configured primary-key column is
 * an IDENTITY column in SQL Server.
 *
 * This allows the repository to support both:
 * - SQL Server generated IDs
 * - Tables where the application must supply the ID
 */
async function identity(
  pool: ConnectionPool,
  c: FormConfig,
): Promise<boolean> {
  const tableName = c.table.replace(/^dbo\./i, "");

  const result = await pool
    .request()
    .input("tableName", sql.NVarChar, tableName)
    .input("columnName", sql.NVarChar, c.idColumn)
    .query(`
      SELECT CAST(
        COLUMNPROPERTY(
          OBJECT_ID('dbo.' + @tableName),
          @columnName,
          'IsIdentity'
        ) AS bit
      ) AS IsIdentity
    `);

  return !!result.recordset[0]?.IsIdentity;
}

/**
 * Generates the next primary-key value for tables where the
 * primary-key column is not configured as an IDENTITY column.
 *
 * NOTE:
 * MAX(ID) + 1 can cause duplicate IDs when multiple users
 * insert records concurrently. Prefer a SQL Server IDENTITY
 * column or SEQUENCE where possible.
 */
async function nextId(
  pool: ConnectionPool,
  c: FormConfig,
): Promise<number> {
  const result = await pool
    .request()
    .query(`
      SELECT ISNULL(MAX([${c.idColumn}]), 0) + 1 AS NextId
      FROM ${c.table}
    `);

  return Number(result.recordset[0].NextId);
}

/**
 * Adds the supplied form values as SQL parameters.
 *
 * Undefined values are converted to NULL so that the SQL
 * statement receives a predictable value for every column.
 */
function inputs(
  req: Request,
  p: InputFormRecord,
  cols: string[],
): void {
  for (const col of cols) {
    req.input(
      col,
      p[col] === undefined ? null : p[col],
    );
  }
}

/**
 * Retrieves all input-form records for a client.
 *
 * The form configuration determines which SQL table and
 * ChildID column are queried.
 */
export async function findByChildId(
  name: FormName,
  childId: number,
) {
  const c = cfg(name);
  const pool = await getPool();

  const result = await pool
    .request()
    .input(c.childIdColumn, sql.Int, childId)
    .query(`
      SELECT *
      FROM ${c.table}
      WHERE [${c.childIdColumn}] = @${c.childIdColumn}
      ORDER BY [${c.idColumn}] DESC
    `);

  return result.recordset;
}

/**
 * Retrieves one input-form record for a client.
 *
 * Both ChildID and record ID are checked to ensure that a user
 * cannot retrieve a form belonging to another client.
 */
export async function findOne(
  name: FormName,
  childId: number,
  id: number,
) {
  const c = cfg(name);
  const pool = await getPool();

  const result = await pool
    .request()
    .input(c.childIdColumn, sql.Int, childId)
    .input(c.idColumn, sql.Int, id)
    .query(`
      SELECT TOP 1 *
      FROM ${c.table}
      WHERE [${c.childIdColumn}] = @${c.childIdColumn}
        AND [${c.idColumn}] = @${c.idColumn}
    `);

  return result.recordset[0] ?? null;
}

/**
 * Inserts a new input-form record.
 *
 * The ChildID supplied by the route is always applied to the
 * record so that the new form is associated with the requested client.
 */
export async function insert(
  name: FormName,
  childId: number,
  payload: InputFormRecord,
) {
  const c = cfg(name);
  const pool = await getPool();

  // Add the route ChildID to the submitted form data.
  const data = clean(c, {
    ...payload,
    [c.childIdColumn]: childId,
  });

  // Determine whether SQL Server generates the primary key.
  const isIdentity = await identity(pool, c);

  const req = pool.request();
  const cols = Object.keys(data);

  // Add form fields as SQL parameters.
  inputs(req, data, cols);

  let names = cols
    .map((column) => `[${column}]`)
    .join(",");

  let values = cols
    .map((column) => `@${column}`)
    .join(",");

  /*
   * If the primary key is not an IDENTITY column,
   * generate the next ID before inserting the record.
   */
  if (!isIdentity) {
    const generatedId = await nextId(pool, c);

    req.input(c.idColumn, sql.Int, generatedId);

    names = `[${c.idColumn}],${names}`;
    values = `@${c.idColumn},${values}`;
  }

  const result = await req.query(`
    INSERT INTO ${c.table} (${names})
    VALUES (${values});

    SELECT TOP 1 *
    FROM ${c.table}
    WHERE [${c.childIdColumn}] = @${c.childIdColumn}
    ${
      isIdentity
        ? `ORDER BY [${c.idColumn}] DESC`
        : `AND [${c.idColumn}] = @${c.idColumn}`
    }
  `);

  return result.recordset[0];
}

/**
 * Updates an existing input-form record.
 *
 * The ChildID and record ID are both used in the WHERE clause
 * to ensure that only the requested client's record is modified.
 */
export async function update(
  name: FormName,
  childId: number,
  id: number,
  payload: InputFormRecord,
) {
  const c = cfg(name);
  const pool = await getPool();

  const data = clean(c, {
    ...payload,
    [c.childIdColumn]: childId,
  });

  // ChildID identifies the client but should not be changed
  // as part of an update.
  const cols = Object.keys(data).filter(
    (column) => column !== c.childIdColumn,
  );

  // Nothing to update; return the existing record.
  if (!cols.length) {
    return findOne(name, childId, id);
  }

  const req = pool
    .request()
    .input(c.childIdColumn, sql.Int, childId)
    .input(c.idColumn, sql.Int, id);

  // Add update values as SQL parameters.
  inputs(req, data, cols);

  const setClause = cols
    .map((column) => `[${column}] = @${column}`)
    .join(",");

  const result = await req.query(`
    UPDATE ${c.table}
    SET
      ${setClause},
      [LastUpdateDate] = GETDATE()
    WHERE [${c.idColumn}] = @${c.idColumn}
      AND [${c.childIdColumn}] = @${c.childIdColumn};

    SELECT TOP 1 *
    FROM ${c.table}
    WHERE [${c.idColumn}] = @${c.idColumn}
      AND [${c.childIdColumn}] = @${c.childIdColumn}
  `);

  return result.recordset[0] ?? null;
}

/**
 * Deletes an input-form record.
 *
 * Both the form ID and ChildID are checked so that the delete
 * operation is restricted to the requested client's record.
 */
export async function remove(
  name: FormName,
  childId: number,
  id: number,
) {
  const c = cfg(name);
  const pool = await getPool();

  const result = await pool
    .request()
    .input(c.childIdColumn, sql.Int, childId)
    .input(c.idColumn, sql.Int, id)
    .query(`
      DELETE FROM ${c.table}
      WHERE [${c.idColumn}] = @${c.idColumn}
        AND [${c.childIdColumn}] = @${c.childIdColumn}
    `);

  return result.rowsAffected[0] > 0;
}