import type { FormConfig, FormName } from "./input-form.types";
export const FORM_CONFIGS: Record<FormName, FormConfig> = {
active:{name:"active",table:"dbo.stblActiveForm",idColumn:"ID",childIdColumn:"ChildID",writableColumns:["ChildID","FormDate","FormType","Region","MonthReporting","SU_id","SUName","CountyCode","Town","FamilyIsSvcCord","SvcCordFirstName","SvcCordLastName","SvcCordType","SvcCordOtherDesc","CAPTA","ReferralDate","ReReferralDate","Address","ZipCode","Ethnicity","InterimDate","InitialEvalDate","EvalWithin45Days","DelayFC","DelayFCOther","DelayNotFC","DelayNotFCOther","InitEval45Compliant","InitEval45FC","InitEval45NC","InitialMeetingDate","MeetingWithin45Days","MeetingDelayFC","MeetingDelayFCOther","MeetingDelayNC","MeetingDelayNCOther","InitMeeting45Compliant","InitMeeting45FC","InitMeeting45NC","BothCompliant","BothFC","BothNC","DDAll","DDAdaptive","DDCognitive","DDCommunication","DDMotor","DDSocial","DCAttachment","DCAutism","DCSuspected","DCBlind","DCDeaf","DCDown","DCCerebral","DCCraniofacial","DCFragile","DCOral","DCBirth","DCOther","DCOtherDesc","ConsentDate","InsertUser","LastUpdateDate","LastUpdateUser","AutismDate","SuspectedDate","BlindDate","DeafDate"]},
"cos-cover":{name:"cos-cover",table:"dbo.stblCOSCoverForm",idColumn:"COSCoverID",childIdColumn:"ChildID",writableColumns:["ChildID","FormDate","FormType","Region","OnePlanDate","EntryOrExit","EligCommunication","EligMildDelay","EligSignificantDelay","EligAutism","EligCerebralPalsy","EligVision","EligOther","EligOtherDesc","Ethnicity","CAPTAReferral","ExitDate","TimeInProgram","SvcChildCare","SvcSpecChildCare","SvcHeadStart","SvcECMH","SvcFamilySupport","SvcNursing","SvcCSHN","SvcReachUp","SvcWIC","LevelOfServices","LevelOfServicesOtherDesc","Outcome1","Outcome1Support","NewSkills1","NewSkills1Explain","Outcome2","Outcome2Support","NewSkills2","NewSkills2Explain","Outcome3","Outcome3Support","NewSkills3","NewSkills3Explain","InsertUser","LastUpdateDate","LastUpdateUser"]},
exit:{name:"exit",table:"dbo.stblExitForm",idColumn:"ID",childIdColumn:"ChildID",writableColumns:["ChildID","FormDate","FormType","Region","MonthReporting","SU_id","SUName","CountyCode","Town","SvcCordFirstName","SvcCordLastName","SvcCordType","SvcCordOtherDesc","CAPTA","ReferralDate","ReReferralDate","COSFEnter30Months","COSFEntryForm","COSFEntryFormReason","COSFGot6MonthsSvcs","COSFExitForm","COSFExitFormReason","ExitDate","TransitionPlanCompleted","TransitionPlanReason","CLLEANotificationDate","Notified90Days","NotifiedReason","NotifyStatePartC","TransitionMeeting","TransitionMeeting90day","NoTransitionMtgReason","ExitPriorToAge3","MovedOtherRegion","ExitAtAge3","EXFNoPartB1","EXFNoPartB2","EXFNoPartB3","ReferredTo","InsertUser","LastUpdateDate","LastUpdateUser"]},
insurance:{name:"insurance",table:"dbo.stblInsuranceForm",idColumn:"ID",childIdColumn:"ChildID",writableColumns:["ChildID","FormDate","FormType","InsCoNumber","InsuranceName","BranchAddress","PolicyNumber","CoverageCode","EffectiveDate","EndDate","PolicyHolder","GroupNumber","GroupName","Phone","BillingConsent","ParentSignatureDate","DeclineReasonCap","DeclineReasonPremium","DeclineReasonBenefits","DeclineReasonEligibility","ParentSignatureDate2","InsertUser","LastUpdateDate","LastUpdateUser"]},
"no-one-plan":{name:"no-one-plan",table:"dbo.stblNoOnePlanForm",idColumn:"ID",childIdColumn:"ChildID",writableColumns:["ChildID","FormDate","FormType","Region","MonthReporting","RefStatus","Screening","ReferredBack","StatusDate","InsertUser","LastUpdateDate","LastUpdateUser"]},
referral:{name:"referral",table:"dbo.stblReferralForm",idColumn:"ID",childIdColumn:"ChildID",writableColumns:["ChildID","FormDate","FormType","Region","MonthReporting","SU_id","SUName","CountyCode","Town","FamilyIsSvcCord","SvcCordFirstName","SvcCordLastName","SvcCordType","SvcCordOtherDesc","ReferralDate","ReReferralDate","Ethnicity","PrimaryLanguage","PrimaryLanguageOther","SecondaryLanguage","SecondaryLanguageOther","CAPTAReferral","Custody","EducationalSurrogate","Medicaid","Private","NoInsurance","CSHN","RefSrcCISIntake","RefSrcPrimaryProv","RefSrcChildCare","RefSrcFamily","RefSrcSchool","RefSrcDCF","RefSrcOther","RefSrcOtherDesc","RefConAll","RefConAdaptive","RefConCognitive","RefConCommunication","RefConMotor","RefConSocial","RefConScreening","RefConOther","RefConOtherDesc","InsertUser","LastUpdateDate","LastUpdateUser","NonEarlyIntervention"]},
"service-grid":{name:"service-grid",table:"dbo.stblServiceGridForm",idColumn:"ServiceGridID",childIdColumn:"ChildID",writableColumns:["ChildID","FormDate","FormType","ReferralDate","ConsentDate","InsertUser","LastUpdateDate","LastUpdateUser"]}
};
